pipeline{
    agent any
    tools{
        jdk 'jdk11'
        maven 'maven3'
        
        
    }
    stages{
        stage("git Checkout")
        {
           steps
            {
                 git url: 'https://github.com/veeracloudev/java_ci_cd.git', branch: 'main'
                 sh 'ls -l'
            }

        }
       
        
        
    }    
    }
